[build]
  # The directory to change to before starting a build
  base = "."
  
  # The command to run to build the site
  command = "echo 'No build step required for static site'"
  
  # The directory in which to deploy (relative to the root of the repo)
  publish = "."

[build.environment]
  # Set any environment variables here
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Site information
[context.production]
  command = "echo 'No build step required for static site'"

[context.deploy-preview]
  command = "echo 'No build step required for static site'"

[context.branch-deploy]
  command = "echo 'No build step required for static site'"

# Redirect rules for single-page application
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"